### ISSUE TITLE
android P 怎么取消长按菜单，恢复overview。

### ISSUE THREAD

**Issue by ilyeral** [yuchuangu85/Launcher3-mx#14]
我想将长按菜单修改回以前版本的overview的样子。但是找不到解决方法。望解答。非常感谢！

**Comment by yuchuangu85** [comment]
@ilyeral 这个是我大改的版本，已经恢复不了了，如果想用就用原生的那个吧，我第一个项目Launcher-mx，这个是原生的，很容易改。

**Comment by ilyeral** [comment]
@yuchuangu85 好的，我去尝试一下。再次感谢！

**Comment by ilyeral** [comment]
@yuchuangu85 请教一下，桌面图标拖动判定是否到下一页是通过哪个方法判断的？

**Comment by yuchuangu85** [comment]
> @yuchuangu85 请教一下，桌面图标拖动判定是否到下一页是通过哪个方法判断的？

你参考一下Folder中的onDragOver方法，默认在桌面上没有需要自己添加
