### ISSUE TITLE
编译正式版出来后，无法打开

### ISSUE THREAD

**Issue by uiuikids** [yuchuangu85/Launcher3-mx#15]
编译正式版出来后，桌面无法打开，也无法设置主页面。
有解决的办法吗？

**Comment by yuchuangu85** [comment]
@uiuikids 这个只是改了单层，添加了特效，只开发了一半，还不能用，还在继续开发

**Comment by uiuikids** [comment]
现在有没有可以用的单层launcher呀

**Comment by yuchuangu85** [comment]
@uiuikids 没有，我也没找到，所以想自己写

**Comment by uiuikids** [comment]
我觉得就这样一个单层的launcher也可以了。不需要太花俏的功能

**Comment by yuchuangu85** [comment]
@uiuikids 恩，但是卸载，缩放，插件那些还没有实现，有些代码写了，但是还没有调通，最近没有太多时间搞，可能要到元旦之后了。
