### ISSUE TITLE
请问刚启动时 怎么停留在首页，加载完不跳转到最后一页。

### ISSUE THREAD

**Issue by linhuan1994** [yuchuangu85/Launcher3-mx#16]
请问刚启动时 怎么停留在首页，加载完不跳转到最后一页？谢谢

**Comment by yuchuangu85** [comment]
> 请问刚启动时 怎么停留在首页，加载完不跳转到最后一页？谢谢

在Launcher中：
bindItems(final List<ItemInfo> items, final boolean forceAnimateIcons)
方法中底部，
 mWorkspace.postDelayed(new Runnable() {
                        public void run() {
                            if (mWorkspace != null) {
                                AbstractFloatingView.closeAllOpenViews(Launcher.this, false);

                                mWorkspace.snapToPage(newScreenIndex);
                                mWorkspace.postDelayed(startBounceAnimRunnable,
                                        NEW_APPS_ANIMATION_DELAY);
                            }
                        }
                    }, NEW_APPS_PAGE_MOVE_DELAY);
这个代码snapToPage是滑动

**Comment by yuchuangu85** [comment]
@linhuan1994 
在Launcher中：
bindItems(final List items, final boolean forceAnimateIcons)
方法中底部，
mWorkspace.postDelayed(new Runnable() {
public void run() {
if (mWorkspace != null) {
AbstractFloatingView.closeAllOpenViews(Launcher.this, false);

                            mWorkspace.snapToPage(newScreenIndex);
                            mWorkspace.postDelayed(startBounceAnimRunnable,
                                    NEW_APPS_ANIMATION_DELAY);
                        }
                    }
                }, NEW_APPS_PAGE_MOVE_DELAY);
这个代码snapToPage是滑动

**Comment by linhuan1994** [comment]
非常感谢！！！
