### ISSUE TITLE
如何添加负一屏 

### ISSUE THREAD

**Issue by TwilightKHQ** [yuchuangu85/Launcher3-mx#18]
请问一下 怎么再添加一个简单的负一屏

**Comment by yuchuangu85** [comment]
> 请问一下 怎么再添加一个简单的负一屏

代码中有个CustomContent类，这个就是负一屏的View，在这个里面开发就好了。
另外，BaseFlags这个类中有开关，自己看一下。

**Comment by TwilightKHQ** [comment]
切换到develop分支后看到了 非常感谢
