### ISSUE TITLE
开发第三方负一屏apk

### ISSUE THREAD

**Issue by xiangwencui** [yuchuangu85/Launcher3-mx#19]
public static final String GSA_PACKAGE = "com.codemx.effectcard";// 负一屏包名
public static final String ACTION = "com.codemx.launcher3.WINDOW_OVERLAY";

楼主0417的修改是关于第三方apk与Launcher之间的通信,来显示负一屏的吗?
想问一下这方面的经验,一直没搞懂怎么用这种方法自定义负一屏View.

**Comment by yuchuangu85** [comment]
> public static final String GSA_PACKAGE = "com.codemx.effectcard";// 负一屏包名
> public static final String ACTION = "com.codemx.launcher3.WINDOW_OVERLAY";
> 
> 楼主0417的修改是关于第三方apk与Launcher之间的通信,来显示负一屏的吗?
> 想问一下这方面的经验,一直没搞懂怎么用这种方法自定义负一屏View.

这种方式是通过AIDL跨进程通信，负一屏是单独的进程，负一屏是一个Window，桌面通过AIDL将滑动进度这些传递给负一屏进程，负一屏根据滑动来加载负一屏视图，这种是谷歌原生的加载负一屏方式，不过我们第三方桌面的话最好不用，因为没有window权限，需要申请，就会有不打开的情况，最好是和桌面绑定，这样不需要权限。

**Comment by TwilightKHQ** [comment]
@yuchuangu85 看了你的源码之后 发现里面也有通过AIDL方式开启负一屏的 但是一直没有显示成功 想问一下这一部分开发已经完成了嘛？ 需要如何开启

**Comment by yuchuangu85** [comment]
> @yuchuangu85 看了你的源码之后 发现里面也有通过AIDL方式开启负一屏的 但是一直没有显示成功 想问一下这一部分开发已经完成了嘛？ 需要如何开启

我还没有写完，不过功能完了，你要做的就是window权限，然后就是操作window就可以了

**Comment by TwilightKHQ** [comment]
window权限该如何添加呢？ 能说的详细一点吗？ launcher开发这一块刚开始做 不熟悉 非常感谢

**Comment by yuchuangu85** [comment]
> window权限该如何添加呢？ 能说的详细一点吗？ launcher开发这一块刚开始做 不熟悉 非常感谢

权限代码在floatwindow的module下面，你在启动AIDL连接负一屏服务的时候就要先去判断是否有权限，没有就要申请，申请通过才能创建Window，不过这个你要优化一下代码，比较乱，我只是加了，没有整理

**Comment by TwilightKHQ** [comment]
我看了一下当前的跨进程负一屏手动开启权限时是可以显示负一屏的 
想了解一下负一屏该如何与桌面进行绑定呢？

**Comment by yuchuangu85** [comment]
> 我看了一下当前的跨进程负一屏手动开启权限时是可以显示负一屏的
> 想了解一下负一屏该如何与桌面进行绑定呢？

FeatureFlags.LAUNCHER_OVERLAY_ENABLED 这个是控制开关，会初始化LauncherClient这个类，这个里面会通过绑定服务，绑定的服务就是FloatWindow那边的，FloatWindow就是在服务那边初始化的。
