### ISSUE TITLE
在预览模式隐藏负一屏

### ISSUE THREAD

**Issue by TwilightKHQ** [yuchuangu85/Launcher3-mx#21]
请问一下该如何在开启双指捏掐预览模式的情况下 隐藏负一屏的预览界面？

**Comment by yuchuangu85** [comment]
> 请问一下该如何在开启双指捏掐预览模式的情况下 隐藏负一屏的预览界面？

在PinchToOverviewListener这个类中有开始和结束的方法，在开始的时候删除负一屏，恢复时添加负一屏就可以了
