### ISSUE TITLE
博主，负一屏开发有问题想请教一下

### ISSUE THREAD

**Issue by 1136066873** [yuchuangu85/Launcher3-mx#22]
博主你好，我现在有一个需求，是基于Android P 的原生 Launcher 添加一个负一屏应用（负一屏需由我来开发），现在搜索了大量的博客，发现都基本上是在传抄同一篇博客：
https://blog.csdn.net/u013032242/article/details/82885110

但是，说实话，参考这个博客，我也对负一屏实现懵懵懂懂​。

看到博主你这里是基于 Android P 的 Launcher 做的修改，并且看提交记录，还实现了负一屏相关，所以想请教一下博主，你有没有把负一屏相关的实现总结过博客，想参考一下你的实现。

急求哇，多谢博主!

**Comment by yuchuangu85** [comment]
> 博主你好，我现在有一个需求，是基于Android P 的原生 Launcher 添加一个负一屏应用（负一屏需由我来开发），现在搜索了大量的博客，发现都基本上是在传抄同一篇博客：
> https://blog.csdn.net/u013032242/article/details/82885110
> 
> 但是，说实话，参考这个博客，我也对负一屏实现懵懵懂懂​。
> 
> 看到博主你这里是基于 Android P 的 Launcher 做的修改，并且看提交记录，还实现了负一屏相关，所以想请教一下博主，你有没有把负一屏相关的实现总结过博客，想参考一下你的实现。
> 
> 急求哇，多谢博主!

你发的博客中说的两种负一屏我代码中都有，一个是在launcher中的，实现相对容易，但是修改代码较多，另外一种是通过AIDL跨进程通信，在另外一个进程启动Window来作为负一屏，但是需要Window权限。

第一种：CustomContent这个类就是负一屏界面，查找下面这个注释就是添加代码的地方：
// add by codemx.cn ---- 20190712 ---plus

第二种：BaseFlags中有个开关，但是我只写了通信部分，没有写Window的详细操作

launcher的博客是很早写的，暂时没有写了，所以只有代码没有详细的博客教程。

**Comment by 1136066873** [comment]
> > 博主你好，我现在有一个需求，是基于Android P 的原生 Launcher 添加一个负一屏应用（负一屏需由我来开发），现在搜索了大量的博客，发现都基本上是在传抄同一篇博客：
> > https://blog.csdn.net/u013032242/article/details/82885110
> > 但是，说实话，参考这个博客，我也对负一屏实现懵懵懂懂​。
> > 看到博主你这里是基于 Android P 的 Launcher 做的修改，并且看提交记录，还实现了负一屏相关，所以想请教一下博主，你有没有把负一屏相关的实现总结过博客，想参考一下你的实现。
> > 急求哇，多谢博主!
> 
> 你发的博客中说的两种负一屏我代码中都有，一个是在launcher中的，实现相对容易，但是修改代码较多，另外一种是通过AIDL跨进程通信，在另外一个进程启动Window来作为负一屏，但是需要Window权限。
> 
> 第一种：CustomContent这个类就是负一屏界面，查找下面这个注释就是添加代码的地方：
> // add by codemx.cn ---- 20190712 ---plus
> 
> 第二种：BaseFlags中有个开关，但是我只写了通信部分，没有写Window的详细操作
> 
> launcher的博客是很早写的，暂时没有写了，所以只有代码没有详细的博客教程。

谢谢博主及时回复，我去看看第二种实现方案去，毕竟 Android P 的 Launcher 中，第一种实现方式相关接口 google 已经去掉了 - -

**Comment by XyfAndZy** [comment]
> 博主你好，我现在有一个需求，是基于Android P 的原生 Launcher 添加一个负一屏应用（负一屏需由我来开发），现在搜索了大量的博客，发现都基本上是在传抄同一篇博客：
> https://blog.csdn.net/u013032242/article/details/82885110
> 
> 但是，说实话，参考这个博客，我也对负一屏实现懵懵懂懂​。
> 
> 看到博主你这里是基于 Android P 的 Launcher 做的修改，并且看提交记录，还实现了负一屏相关，所以想请教一下博主，你有没有把负一屏相关的实现总结过博客，想参考一下你的实现。
> 
> 急求哇，多谢博主!

共同学习下，我这两天也在准备负一屏相关资料预研，感谢博主提供得代码
