### ISSUE TITLE
studio4.0.1加载这个项目时报错

### ISSUE THREAD

**Issue by LiaoJXin** [yuchuangu85/Launcher3-mx#24]
头一次开发车载launcher，云里雾里的，看着你的这个项目不错，想拉下来学习，然而编译时出错，不是很懂，特来请教。
bug如下：
Task :effectivecard:compileDebugJavaWithJavac FAILED
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:9: ����: �Ҳ�������
import com.codemx.effectivecard.launcherclient.ILauncherOverlay;
                                              ^
  ����:   �� ILauncherOverlay
  λ��: ����� com.codemx.effectivecard.launcherclient
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:10: ����: �Ҳ�������
import com.codemx.effectivecard.launcherclient.ILauncherOverlayCallback;
                                              ^
  ����:   �� ILauncherOverlayCallback
  λ��: ����� com.codemx.effectivecard.launcherclient
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:23: ����: �����ILauncherOverlay������
    private ILauncherOverlay.Stub mStub;
                            ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:56: ����: �����ILauncherOverlay������
    private static class CardBinder extends ILauncherOverlay.Stub {
                                                            ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\IWindowCallback.java:3: ����: �Ҳ�������
import com.codemx.effectivecard.launcherclient.ILauncherOverlayCallback;
                                              ^
  ����:   �� ILauncherOverlayCallback
  λ��: ����� com.codemx.effectivecard.launcherclient
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:91: ����: �Ҳ�������
        public void windowAttached(MxLayoutParams layoutParams, ILauncherOverlayCallback overlayCallback, int flags) throws RemoteException {
                                                                ^
  ����:   �� ILauncherOverlayCallback
  λ��: �� CardBinder
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\IWindowCallback.java:23: ����: �Ҳ�������
    void windowAttached(MxLayoutParams layoutParams, ILauncherOverlayCallback overlayCallback, int flags);
                                                     ^
  ����:   �� ILauncherOverlayCallback
  λ��: �ӿ� IWindowCallback
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardWindowManager.java:14: ����: �Ҳ�������
import com.codemx.effectivecard.launcherclient.ILauncherOverlayCallback;
                                              ^
  ����:   �� ILauncherOverlayCallback
  λ��: ����� com.codemx.effectivecard.launcherclient
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardWindowManager.java:78: ����: �Ҳ�������
    private ILauncherOverlayCallback mOverlayCallback;
            ^
  ����:   �� ILauncherOverlayCallback
  λ��: �� CardWindowManager
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardWindowManager.java:98: ����: �Ҳ�������
    public void windowAttached(final MxLayoutParams layoutParams, ILauncherOverlayCallback overlayCallback, int flags) {
                                                                  ^
  ����:   �� ILauncherOverlayCallback
  λ��: �� CardWindowManager
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\launcherclient\LauncherClient.java:40: ����: �Ҳ�������
    private ILauncherOverlay mOverlay;
            ^
  ����:   �� ILauncherOverlay
  λ��: �� LauncherClient
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\launcherclient\LauncherOverlayCallbacks.java:19: ����: �����ILauncherOverlayCallback������
public class LauncherOverlayCallbacks extends ILauncherOverlayCallback.Stub implements Handler.Callback {
                                                                      ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:63: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:72: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:81: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:90: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:99: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:108: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:117: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:126: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:135: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:144: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:153: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:162: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:171: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:180: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:189: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\CardService.java:197: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
        @Override
        ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\launcherclient\LauncherClient.java:408: ����: �����ILauncherOverlay������
                mClient.mOverlay = ILauncherOverlay.Stub.asInterface(service);
                                                   ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\launcherclient\LauncherClient.java:441: ����: �����ILauncherOverlay������
            LauncherClient.this.mOverlay = ILauncherOverlay.Stub.asInterface(service);
                                                           ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\launcherclient\LauncherOverlayCallbacks.java:64: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
    @Override
    ^
E:\Launcher3-mx-develop\effectivecard\src\main\java\com\codemx\effectivecard\launcherclient\LauncherOverlayCallbacks.java:69: ����: �������Ḳ�ǻ�ʵ�ֳ����͵ķ���
    @Override
    ^
32 ������
///////////////////////////////////////////////////////////////////////////////
看着，都是缺失这么些类：
import com.codemx.effectivecard.launcherclient.ILauncherOverlay;
import com.codemx.effectivecard.launcherclient.ILauncherOverlayCallback;
以及 ILauncherOverlay
全局查找，以为是如下的类，发现不是：
import com.google.android.libraries.launcherclient.ILauncherOverlay;
import com.google.android.libraries.launcherclient.ILauncherOverlayCallback;
特来请教一下，是什么问题

**Comment by yuchuangu85** [comment]
@UltraXin 这个是AIDL文件自动生成的，你要先build一下，然后会自动生成这些文件

**Comment by LiaoJXin** [comment]
@yuchuangu85 
我将mxtheme文件夹下的build里的所有文件都删除了，然后livalidate caches/restart，或者rebuild都不能成功。
报错：
> Task :mxtheme:compileDebugJavaWithJavac FAILED
E:\Launcher3-mx-develop\mxtheme\build\generated\aidl_source_output_dir\debug\out\com\android\mxtheme\IRemoteCallback.java:114: ����: ����ʱ�ѵ����ļ���β
1 ������

> Task :floatwindow:mergeDebugNativeLibs

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mxtheme:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
49 actionable tasks: 41 executed, 8 up-to-date

**Comment by yuchuangu85** [comment]
@UltraXin 你更新一下代码，用develop分支，有个属性iconSize与Google的Material主题包中的一样。导致编译不过
