### ISSUE TITLE
Option to remove app drawer

### ISSUE THREAD

**Issue by qw123wh** [yuchuangu85/Launcher3-mx#32]
Add the ability to remove the app drawer, as it happens for most of the existing stock launchers, such as: oneplus, motorola, xiaomi, huawei, ect ...

**Comment by yuchuangu85** [comment]
@qw123wh This version of code is older, I will update the code version to Android T, so this code will not modify, only fix some bugs, but i need some time to update the code.

**Comment by yuchuangu85** [comment]
@qw123wh You can use this project https://github.com/Launcher3-dev/MXLauncher, this project base the newest Launcher 
 (Android 13) , I add the option close or open drawer in setting

**Comment by qw123wh** [comment]
@yuchuangu85 thanks, if you can release an apk in that project to try it out.  Otherwise I would have to build it myself with Android studio it takes more time for me. Anyway I'll try it and let you know

**Comment by qw123wh** [comment]
@yuchuangu85 thanks, I tried the app and it works great. If you work on other aosp-based apps and are interested in the aosp clock app, take a look at my project and if you want feel free to fork and some PR https://github.com/qw123wh/new-clock

**Comment by yuchuangu85** [comment]
@qw123wh I stared it. How to use github action to build apk and upload, I try many time failed.

**Comment by qw123wh** [comment]
yesterday I managed to download the apk from the folder

https://github.com/Launcher3-dev/MXLauncher/tree/dev/.github/workflows

Today, however, the apk is no longer present in that folder

The apk file does not send it to me, I compressed it in a .zip file, extract it and you will find the apk

[MXLauncher-aosp-withoutQuickstep-debug.apk.zip](https://github.com/Launcher3-dev/Launcher3-mx/files/9696054/MXLauncher-aosp-withoutQuickstep-debug.apk.zip)

**Comment by yuchuangu85** [comment]
@qw123wh In your project https://github.com/qw123wh/new-clock, 
![image](https://user-images.githubusercontent.com/7369323/193540264-a60e025b-abfa-4947-8670-c4d224ce619c.png)
how to do this? upload apk to github.

**Comment by qw123wh** [comment]
Select the apk file manually from your computer / device


![3FC4F027-E07C-4B67-B30C-F1FBCB66EC5F](https://user-images.githubusercontent.com/59417474/193541119-e3796fe1-01a4-434d-96f3-1a59dc16128a.jpeg)

**Comment by yuchuangu85** [comment]
@qw123wh Ok thank you, I see them using Github Action to automatically generate APK， but I failed.

**Comment by qw123wh** [comment]
I have always generated the apk from Android Studio, then I loaded the apk manually. I don't know how to use github action, I don't remember if anyone has done a PR about it on my project

**Comment by yuchuangu85** [comment]
@qw123wh Thank you, I will upload apk build by AS.
